from uuid import uuid4

ORGANISATIONS = [
    {
        "id": str(uuid4()),
        "name": "Monzo",
        "industry": "fintech",
        "location": "London",
        "description": "Digital challenger bank serving millions of UK customers",
        "size": "1000-5000",
    },
    {
        "id": str(uuid4()),
        "name": "Babylon Health",
        "industry": "healthtech",
        "location": "London",
        "description": "AI-powered healthcare platform providing virtual consultations",
        "size": "500-1000",
    },
    {
        "id": str(uuid4()),
        "name": "Paddle",
        "industry": "SaaS",
        "location": "London",
        "description": "Revenue delivery platform for SaaS companies",
        "size": "200-500",
    },
    {
        "id": str(uuid4()),
        "name": "Starling Bank",
        "industry": "fintech",
        "location": "London",
        "description": "Award-winning mobile-first bank for personal and business banking",
        "size": "1000-5000",
    },
    {
        "id": str(uuid4()),
        "name": "Huma",
        "industry": "healthtech",
        "location": "London",
        "description": "Digital health platform for remote patient monitoring and clinical trials",
        "size": "200-500",
    },
    {
        "id": str(uuid4()),
        "name": "Checkout.com",
        "industry": "fintech",
        "location": "London",
        "description": "Cloud-based payment processing platform for global merchants",
        "size": "1000-5000",
    },
    {
        "id": str(uuid4()),
        "name": "ContentSquare",
        "industry": "SaaS",
        "location": "London",
        "description": "Digital experience analytics platform for enterprise brands",
        "size": "500-1000",
    },
    {
        "id": str(uuid4()),
        "name": "Gousto",
        "industry": "e-commerce",
        "location": "London",
        "description": "Recipe box delivery service with AI-powered menu personalisation",
        "size": "500-1000",
    },
    {
        "id": str(uuid4()),
        "name": "Peak AI",
        "industry": "SaaS",
        "location": "Manchester",
        "description": "AI platform helping businesses optimise decisions through machine learning",
        "size": "100-200",
    },
    {
        "id": str(uuid4()),
        "name": "Multiverse",
        "industry": "edtech",
        "location": "London",
        "description": "Alternative to university providing apprenticeships at top companies",
        "size": "500-1000",
    },
    {
        "id": str(uuid4()),
        "name": "Thought Machine",
        "industry": "fintech",
        "location": "London",
        "description": "Cloud-native core banking technology provider",
        "size": "500-1000",
    },
    {
        "id": str(uuid4()),
        "name": "Onfido",
        "industry": "fintech",
        "location": "London",
        "description": "AI-powered identity verification and authentication platform",
        "size": "500-1000",
    },
]
